version: "3.9"

services:
  chat-service:
    build: ./services/chat-service
    ports:
      - "3001:3000"
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/chatdb
      REDIS_URL: redis://redis:6379
    depends_on:
      - postgres
      - redis

  presence-service:
    build: ./services/presence-service
    ports:
      - "3002:3000"
    depends_on:
      - redis

  relations-service:
    build: ./services/relations-service
    ports:
      - "3003:3000"
    depends_on:
      - postgres
      - redis

  search-service:
    build: ./services/search-service
    ports:
      - "3004:3000"
    environment:
      ELASTIC_URL: http://elasticsearch:9200
    depends_on:
      - elasticsearch

  telegram-bot-service:
    build: ./services/telegram-bot-service
    environment:
      BOT_TOKEN: "YOUR_TOKEN"
    depends_on:
      - chat-service
      - redis

  users-service:
    build: ./services/users-service
    ports:
      - "3005:3000"
    depends_on:
      - postgres
      - redis

  frontend:
    build: ./frontend
    ports:
      - "80:80"

  # Databases & cache
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chatdb
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - "9200:9200"

volumes:
  pgdata:
