export const dummyUsersWithProfiles = [
  {
    id: 1001,
    telegram_id: 1001,
    username: "ahmadreza1",
    profile: {
      first_name: "Ahmadreza",
      last_name: "Rezaei",
      age: 26,
      gender: "male",
      career: "developer",
      interests: ["coding", "music", "gaming"],
      country: "Iran",
      state: "Tehran",
      city: "Tehran",
      latitude: 35.6892,
      longitude: 51.389,
    },
  },
  {
    id: 1002,
    telegram_id: 1002,
    username: "sara_j",
    profile: {
      first_name: "Sara",
      last_name: "Jafari",
      age: 24,
      gender: "female",
      career: "designer",
      interests: ["art", "travel", "reading"],
      country: "Iran",
      state: "Isfahan",
      city: "Isfahan",
      latitude: 32.6546,
      longitude: 51.668,
    },
  },
  {
    id: 1003,
    telegram_id: 1003,
    username: "omid_82",
    profile: {
      first_name: "Omid",
      last_name: "Taheri",
      age: 28,
      gender: "male",
      career: "developer",
      interests: ["coding", "gaming"],
      country: "Iran",
      state: "Shiraz",
      city: "Shiraz",
      latitude: 29.5918,
      longitude: 52.5836,
    },
  },
  {
    id: 1004,
    telegram_id: 1004,
    username: "leila_m",
    profile: {
      first_name: "Leila",
      last_name: "Mansouri",
      age: 25,
      gender: "female",
      career: "teacher",
      interests: ["reading", "travel", "music"],
      country: "Iran",
      state: "Tabriz",
      city: "Tabriz",
      latitude: 38.0962,
      longitude: 46.2738,
    },
  },
  {
    id: 1005,
    telegram_id: 1005,
    username: "navid_t",
    profile: {
      first_name: "Navid",
      last_name: "Tahmasebi",
      age: 27,
      gender: "male",
      career: "developer",
      interests: ["coding", "gaming", "music"],
      country: "Iran",
      state: "Tehran",
      city: "Tehran",
      latitude: 35.6892,
      longitude: 51.389,
    },
  },
  {
    id: 1006,
    telegram_id: 1006,
    username: "mina.r",
    profile: {
      first_name: "Mina",
      last_name: "Ramezani",
      age: 23,
      gender: "female",
      career: "designer",
      interests: ["art", "travel", "music"],
      country: "Iran",
      state: "Mashhad",
      city: "Mashhad",
      latitude: 36.2605,
      longitude: 59.6168,
    },
  },
  {
    id: 1007,
    telegram_id: 1007,
    username: "ali_s",
    profile: {
      first_name: "Ali",
      last_name: "Shirazi",
      age: 29,
      gender: "male",
      career: "manager",
      interests: ["sports", "reading", "coding"],
      country: "Iran",
      state: "Esfahan",
      city: "Isfahan",
      latitude: 32.6546,
      longitude: 51.668,
    },
  },
  {
    id: 1008,
    telegram_id: 1008,
    username: "neda_k",
    profile: {
      first_name: "Neda",
      last_name: "Karimi",
      age: 26,
      gender: "female",
      career: "developer",
      interests: ["coding", "music", "travel"],
      country: "Iran",
      state: "Tehran",
      city: "Tehran",
      latitude: 35.6892,
      longitude: 51.389,
    },
  },
  {
    id: 1009,
    telegram_id: 1009,
    username: "reza_h",
    profile: {
      first_name: "Reza",
      last_name: "Hosseini",
      age: 30,
      gender: "male",
      career: "manager",
      interests: ["sports", "reading", "travel"],
      country: "Iran",
      state: "Shiraz",
      city: "Shiraz",
      latitude: 29.5918,
      longitude: 52.5836,
    },
  },
  {
    id: 1010,
    telegram_id: 1010,
    username: "fatemeh_91",
    profile: {
      first_name: "Fatemeh",
      last_name: "Hosseini",
      age: 24,
      gender: "female",
      career: "student",
      interests: ["coding", "music", "reading"],
      country: "Iran",
      state: "Tehran",
      city: "Tehran",
      latitude: 35.6892,
      longitude: 51.389,
    },
  },
];
